# Generated by Django 5.2.7 on 2026-08-10 19:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_bank',
            },
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Main Cash', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_cash',
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment'), ('OPENING', 'Opening Balance'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('voucher_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'accounts_cash_transactions',
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cheque_number', models.CharField(db_index=True, max_length=50)),
                ('cheque_type', models.CharField(choices=[('ISSUED', 'Issued (Payment)'), ('RECEIVED', 'Received (Income)')], max_length=10)),
                ('date', models.DateField()),
                ('payee_payer', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('RECEIVED', 'Received'), ('DEPOSITED', 'Deposited'), ('PENDING', 'Pending Clearance'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20)),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('clearance_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_cheques',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payee', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('MEDICAL', 'Medical Assistance'), ('EDUCATION', 'Education Assistance'), ('FOOD', 'Food Distribution'), ('CHARITY', 'Charity Programs'), ('TRANSPORT', 'Transportation'), ('OFFICE', 'Office Expenses'), ('UTILITIES', 'Utilities'), ('MAINTENANCE', 'Maintenance'), ('PURCHASE', 'Purchases'), ('SALARY', 'Salary'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('DD', 'Demand Draft'), ('OTHER', 'Other')], max_length=20)),
                ('purpose', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], default='CASH', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='expenses/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('donor_name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('DONATION', 'Donation'), ('GRANT', 'Grant'), ('SPONSORSHIP', 'Sponsorship'), ('MEMBERSHIP', 'Membership Fees'), ('FUNDRAISING', 'Fundraising'), ('INTEREST', 'Interest'), ('OTHER', 'Other Income')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('DD', 'Demand Draft'), ('OTHER', 'Other')], max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], default='CASH', max_length=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='income/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_income',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('DISBURSEMENT', 'Disbursement'), ('SALARY', 'Salary Payment')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], max_length=10)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('DD', 'Demand Draft'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('transfer_type', models.CharField(choices=[('CASH_TO_BANK', 'Cash to Bank'), ('BANK_TO_CASH', 'Bank to Cash'), ('BANK_TO_BANK', 'Bank to Bank')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_transfers',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('CHARGES', 'Bank Charges'), ('INTEREST', 'Interest'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('DD', 'Demand Draft'), ('OTHER', 'Other')], default='NEFT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utr_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts_module.bankaccount')),
            ],
            options={
                'db_table': 'accounts_bank_transactions',
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
