# Generated by Django 5.2.7 on 2026-08-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0003_alter_banktransaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MEDICAL', 'Medical Assistance'), ('EDUCATION', 'Education Assistance'), ('FOOD', 'Food Distribution'), ('CHARITY', 'Charity Programs'), ('TRANSPORT', 'Transportation'), ('OFFICE', 'Office Expenses'), ('UTILITIES', 'Utilities'), ('MAINTENANCE', 'Maintenance'), ('PURCHASE', 'Purchases'), ('OUTWARD', 'Outward Dispatch'), ('SALARY', 'Salary'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('DONATION', 'Donation'), ('GRANT', 'Grant'), ('SPONSORSHIP', 'Sponsorship'), ('MEMBERSHIP', 'Membership Fees'), ('FUNDRAISING', 'Fundraising'), ('INTEREST', 'Interest'), ('INWARD', 'Inward Receipt'), ('OTHER', 'Other Income')], max_length=20),
        ),
    ]
