# Generated by Django 5.2.7 on 2026-08-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0004_alter_expense_category_alter_income_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
