# Generated by Django 5.2.7 on 2026-08-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0005_income_donor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='whatsapp_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
