# Generated by Django 5.2.7 on 2026-08-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0006_income_whatsapp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='bill_book_end',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='income',
            name='bill_book_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='income',
            name='bill_book_start',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
