# Generated by Django 5.2.7 on 2026-08-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0007_income_bill_book_end_income_bill_book_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
