# Generated by Django 5.2.7 on 2026-08-24 08:39

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0008_income_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='expenses/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='income',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='income/', validators=[core.validators.validate_document_file]),
        ),
    ]
