# Generated by Django 5.2.7 on 2026-08-26 10:33

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0009_alter_expense_document_alter_income_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='ifsc_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='donor_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
