# Generated by Django 5.2.7 on 2026-08-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0010_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
