# Generated by Django 5.2.7 on 2026-09-01 21:55

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0011_transfer_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='donor_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
