# Generated by Django 5.2.7 on 2026-09-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0012_donor_phone_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date', '-created_at']},
        ),
    ]
