# Generated by Django 5.2.7 on 2026-09-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0014_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
