# Generated by Django 5.2.7 on 2026-09-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0015_alter_expense_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
