# Generated by Django 5.2.7 on 2026-09-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0016_alter_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
