# Generated by Django 5.2.7 on 2026-09-22 14:06

from django.db import migrations


def fix_account_types(apps, schema_editor):
    Income = apps.get_model('accounts_module', 'Income')
    
    # List of payment methods that should always be BANK
    bank_methods = ['UPI', 'NEFT', 'RTGS', 'IMPS', 'CHEQUE', 'DD']
    
    # Update existing records where payment method is one of the above, but account_type is 'CASH'
    updated = Income.objects.filter(
        payment_method__in=bank_methods, 
        account_type='CASH'
    ).update(account_type='BANK')
    
    print(f"Fixed {updated} income records to use BANK account type.")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0018_expense_reference_number_expense_remarks_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_account_types),
    ]

