# Generated by Django 5.2.7 on 2026-08-10 19:58

import django.db.models.deletion
import django.utils.timezone
import manager_module.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('request_type', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('MEDICAL', 'Medical Assistance'), ('EDUCATION', 'Education Assistance'), ('FOOD', 'Food Distribution'), ('CHARITY', 'Charity Program'), ('TRANSPORT', 'Transportation'), ('OFFICE', 'Office Expenses'), ('UTILITIES', 'Utilities'), ('MAINTENANCE', 'Maintenance'), ('PURCHASE', 'Purchase'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ON_HOLD', 'On Hold'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CASHIER_PENDING', 'Cashier Pending'), ('DISBURSED', 'Disbursed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('purpose', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_disbursed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=255)),
                ('beneficiary_contact', models.CharField(blank=True, max_length=20)),
                ('manager_remarks', models.TextField(blank=True)),
                ('accountant_remarks', models.TextField(blank=True)),
                ('cashier_remarks', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('hold_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=manager_module.models.request_doc_path)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MinutesRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('meeting_date', models.DateField()),
                ('meeting_type', models.CharField(choices=[('BOARD', 'Board Meeting'), ('GENERAL', 'General Meeting'), ('COMMITTEE', 'Committee Meeting'), ('EMERGENCY', 'Emergency Meeting'), ('ANNUAL', 'Annual General Meeting'), ('OTHER', 'Other')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('chairperson', models.CharField(max_length=255)),
                ('participants', models.JSONField(default=list)),
                ('agenda', models.TextField()),
                ('discussions', models.TextField(blank=True)),
                ('decisions', models.TextField(blank=True)),
                ('action_items', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='minutes/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_minutes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_minutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_minutes',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(choices=[('CLUB', 'Club'), ('GROUP', 'Group'), ('ASSOCIATION', 'Association'), ('LOCAL_TEAM', 'Local Team'), ('NGO', 'NGO'), ('GOVERNMENT', 'Government Body'), ('OTHER', 'Other')], max_length=20)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='partners/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_partners',
                'ordering': ['organization_name'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='manager_module.assessmentrequest')),
            ],
            options={
                'db_table': 'manager_request_status_history',
                'ordering': ['timestamp'],
            },
        ),
    ]
