# Generated by Django 5.2.7 on 2026-08-12 15:51

import django.db.models.deletion
import django.utils.timezone
import manager_module.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0002_alter_executiveofficer_joining_date_and_more'),
        ('manager_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentrequest',
            old_name='beneficiary_contact',
            new_name='beneficiary_phone',
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='assigned_aco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aco_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='assigned_fao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fao_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='assigned_geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='beneficiary_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='beneficiary_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='beneficiary_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='beneficiary_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='eligibility',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='hr_module.member'),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='source',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('MEMBER', 'Member'), ('WALK_IN', 'Walk-In')], default='STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentrequest',
            name='amount_requested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentrequest',
            name='category',
            field=models.CharField(choices=[('MEDICAL', 'Medical Assistance'), ('EDUCATION', 'Education Assistance'), ('FOOD', 'Food Assistance'), ('HOUSING', 'Housing / Construction'), ('LIVELIHOOD', 'Livelihood Support'), ('DISABILITY', 'Disability Support'), ('ELDERLY', 'Elderly Care'), ('CHILD_WELFARE', 'Child Welfare'), ('WOMEN_WELFARE', 'Women Welfare'), ('CHARITY', 'Charity Program'), ('TRANSPORT', 'Transportation'), ('OFFICE', 'Office Expenses'), ('UTILITIES', 'Utilities'), ('MAINTENANCE', 'Maintenance'), ('PURCHASE', 'Purchase'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentrequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='assessmentrequest',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assessmentrequest',
            name='request_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assessmentrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('WITH_FAO', 'With Field Assessment Officer'), ('WITH_ACO', 'With Assessment Calculation Officer'), ('WITH_GEO', 'With General Enquiry Officer'), ('FAO_REJECTED', 'Rejected by FAO'), ('ON_HOLD', 'On Hold'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CASHIER_PENDING', 'Cashier Pending'), ('DISBURSED', 'Disbursed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20),
        ),
        migrations.CreateModel(
            name='ACOCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_items', models.JSONField(default=list)),
                ('has_recurring_cost', models.BooleanField(default=False)),
                ('recurring_monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recurring_duration_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recurring_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_one_time_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recommended_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('justification', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aco_calculation', to='manager_module.assessmentrequest')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aco_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_aco_calculations',
            },
        ),
        migrations.CreateModel(
            name='CharityInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('MEDICINE', 'Medicine'), ('EQUIPMENT', 'Equipment / Mobility Aids'), ('FOOD', 'Food Supplies'), ('CLOTHING', 'Clothing'), ('EDUCATION', 'Educational Materials'), ('CONSTRUCTION', 'Construction Materials'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='unit', max_length=50)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Charity Inventory',
                'db_table': 'manager_charity_inventory',
                'ordering': ['category', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='FAOReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficiary_verified_name', models.CharField(blank=True, max_length=255)),
                ('beneficiary_verified_address', models.TextField(blank=True)),
                ('beneficiary_verified_phone', models.CharField(blank=True, max_length=20)),
                ('address_corrections', models.TextField(blank=True)),
                ('ex_ward_member_name', models.CharField(blank=True, max_length=255)),
                ('ex_ward_member_position', models.CharField(blank=True, max_length=255)),
                ('ex_ward_member_report', models.TextField(blank=True)),
                ('ex_ward_member_signature_photo', models.ImageField(blank=True, null=True, upload_to='fao_signatures/')),
                ('current_ward_member_name', models.CharField(blank=True, max_length=255)),
                ('current_ward_member_position', models.CharField(blank=True, max_length=255)),
                ('current_ward_member_report', models.TextField(blank=True)),
                ('current_ward_member_signature_photo', models.ImageField(blank=True, null=True, upload_to='fao_signatures/')),
                ('neighbour_1_name', models.CharField(blank=True, max_length=255)),
                ('neighbour_1_relationship', models.CharField(blank=True, max_length=100)),
                ('neighbour_1_statement', models.TextField(blank=True)),
                ('neighbour_2_name', models.CharField(blank=True, max_length=255)),
                ('neighbour_2_relationship', models.CharField(blank=True, max_length=100)),
                ('neighbour_2_statement', models.TextField(blank=True)),
                ('officer_findings', models.TextField(blank=True)),
                ('visit_location_lat', models.FloatField(blank=True, null=True)),
                ('visit_location_lng', models.FloatField(blank=True, null=True)),
                ('visit_location_text', models.CharField(blank=True, max_length=500)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('category_confirmed', models.CharField(blank=True, choices=[('MEDICAL', 'Medical Assistance'), ('EDUCATION', 'Education Assistance'), ('FOOD', 'Food Assistance'), ('HOUSING', 'Housing / Construction'), ('LIVELIHOOD', 'Livelihood Support'), ('DISABILITY', 'Disability Support'), ('ELDERLY', 'Elderly Care'), ('CHILD_WELFARE', 'Child Welfare'), ('WOMEN_WELFARE', 'Women Welfare'), ('CHARITY', 'Charity Program'), ('TRANSPORT', 'Transportation'), ('OFFICE', 'Office Expenses'), ('UTILITIES', 'Utilities'), ('MAINTENANCE', 'Maintenance'), ('PURCHASE', 'Purchase'), ('OTHER', 'Other')], max_length=20)),
                ('urgency_assessment', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('eligibility', models.CharField(choices=[('PENDING', 'Pending'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible')], default='PENDING', max_length=15)),
                ('eligibility_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fao_report', to='manager_module.assessmentrequest')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fao_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_fao_reports',
            },
        ),
        migrations.CreateModel(
            name='FAOPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=manager_module.models.fao_photo_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='manager_module.faoreport')),
            ],
            options={
                'db_table': 'manager_fao_photos',
            },
        ),
        migrations.CreateModel(
            name='GEOReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_findings', models.TextField(blank=True)),
                ('discrepancies_found', models.TextField(blank=True)),
                ('field_notes', models.TextField(blank=True)),
                ('visit_location_lat', models.FloatField(blank=True, null=True)),
                ('visit_location_lng', models.FloatField(blank=True, null=True)),
                ('visit_location_text', models.CharField(blank=True, max_length=500)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation', models.CharField(choices=[('APPROVE_AS_IS', 'Approve As-Is'), ('APPROVE_WITH_CHANGES', 'Approve with Changes'), ('REJECT', 'Reject'), ('FURTHER_REVIEW', 'Needs Further Review')], default='APPROVE_AS_IS', max_length=25)),
                ('recommended_amount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('recommendation_justification', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_report', to='manager_module.assessmentrequest')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_geo_reports',
            },
        ),
        migrations.CreateModel(
            name='GEOPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=manager_module.models.geo_photo_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='manager_module.georeport')),
            ],
            options={
                'db_table': 'manager_geo_photos',
            },
        ),
    ]
