# Generated by Django 5.2.7 on 2026-08-15 10:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_module', '0002_rename_beneficiary_contact_assessmentrequest_beneficiary_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('transaction_type', models.CharField(choices=[('INWARD', 'Inward'), ('OUTWARD', 'Outward')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='manager_module.charityinventory')),
            ],
            options={
                'db_table': 'manager_inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
