# Generated by Django 5.2.7 on 2026-08-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_module', '0005_scheduledpayout_delete_charityprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentrequest',
            name='scheduled_payout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
