# Generated by Django 5.2.7 on 2026-08-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_module', '0006_assessmentrequest_scheduled_payout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('WITH_FAO', 'With Field Assessment Officer'), ('WITH_ACO', 'With Assessment Calculation Officer'), ('WITH_GEO', 'With General Enquiry Officer'), ('FAO_REJECTED', 'Rejected by FAO'), ('ON_HOLD', 'On Hold'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING_DISBURSEMENT', 'Pending Disbursement'), ('DISBURSED', 'Disbursed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20),
        ),
    ]
