# Generated by Django 5.2.7 on 2026-08-24 08:39

import core.validators
import manager_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_module', '0007_alter_assessmentrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=manager_module.models.request_doc_path, validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='faophoto',
            name='image',
            field=models.ImageField(upload_to=manager_module.models.fao_photo_path, validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='faoreport',
            name='current_ward_member_signature_photo',
            field=models.ImageField(blank=True, null=True, upload_to='fao_signatures/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='faoreport',
            name='ex_ward_member_signature_photo',
            field=models.ImageField(blank=True, null=True, upload_to='fao_signatures/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='geophoto',
            name='image',
            field=models.ImageField(upload_to=manager_module.models.geo_photo_path, validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='minutesregistry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='minutes/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='partners/', validators=[core.validators.validate_document_file]),
        ),
    ]
