# Generated by Django 5.2.7 on 2026-08-26 10:33

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_module', '0008_alter_assessmentrequest_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentrequest',
            name='beneficiary_address',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessmentrequest',
            name='beneficiary_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='faoreport',
            name='beneficiary_verified_address',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faoreport',
            name='beneficiary_verified_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
