# Generated by Django 5.2.7 on 2026-08-30 18:45

import manager_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_module', '0009_alter_assessmentrequest_beneficiary_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentrequest',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to=manager_module.models.request_doc_path),
        ),
    ]
