# Generated by Django 5.2.7 on 2026-09-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_module', '0010_assessmentrequest_voice_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityinventory',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
