# Generated by Django 5.2.7 on 2026-09-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_module', '0011_alter_charityinventory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='dispatched_to',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
