# Generated by Django 5.2.7 on 2026-09-26 17:22

import core.validators
import django.db.models.deletion
import django.utils.timezone
import manager_module.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_module', '0012_inventorytransaction_dispatched_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=manager_module.models.request_doc_path, validators=[core.validators.validate_image_file])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='manager_module.assessmentrequest')),
            ],
            options={
                'db_table': 'manager_assessment_photos',
            },
        ),
    ]
