# Generated by Django 5.2.7 on 2026-08-12 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiveofficer',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='member',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
