# Generated by Django 5.2.7 on 2026-08-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0002_alter_executiveofficer_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='member',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
