# Generated by Django 5.2.7 on 2026-08-18 08:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0005_paymentadvancerequest_performancepoint_staffreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('pdf_file', models.FileField(upload_to='membership_receipts/')),
                ('whatsapp_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='hr_module.member')),
            ],
            options={
                'db_table': 'hr_membership_receipts',
                'ordering': ['-generated_at'],
            },
        ),
    ]
