# Generated by Django 5.2.7 on 2026-08-24 08:39

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0006_membershipreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to='hr/employee_docs/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='executivemember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hr/exec_members/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='executiveofficer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hr/officers/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='hr/leaves/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hr/members/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='file',
            field=models.FileField(upload_to='hr/member_docs/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='membershipreceipt',
            name='pdf_file',
            field=models.FileField(upload_to='membership_receipts/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='staffreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='hr/reports/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hr/volunteers/', validators=[core.validators.validate_image_file]),
        ),
    ]
