# Generated by Django 5.2.7 on 2026-08-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0008_alter_executivemember_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentadvancerequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
