# Generated by Django 5.2.7 on 2026-08-29 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0009_alter_paymentadvancerequest_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffVoucherBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_number', models.PositiveIntegerField(default=1, help_text='Voucher book number (e.g. 1, 2, 3)')),
                ('voucher_start', models.PositiveIntegerField(default=1, help_text='First voucher number in the book')),
                ('voucher_end', models.PositiveIntegerField(default=100, help_text='Last voucher number in the book')),
                ('current_voucher', models.PositiveIntegerField(default=1, help_text='Next voucher to be issued')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_book', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_staff_voucher_books',
            },
        ),
    ]
