# Generated by Django 5.2.7 on 2026-08-29 10:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0010_staff_voucher_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoterRegistryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('entry_code', models.CharField(help_text='e.g. VR250528001', max_length=50, unique=True)),
                ('starting_reading', models.PositiveIntegerField()),
                ('ending_reading', models.PositiveIntegerField()),
                ('promoter_reading', models.PositiveIntegerField(help_text='Calculated: ending - starting + 1')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('online_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoter_registry_creations', to=settings.AUTH_USER_MODEL)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoter_registry_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_promoter_registry',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
