# Generated by Django 5.2.7 on 2026-08-29 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0011_promoterregistryentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promoterregistryentry',
            unique_together={('promoter', 'date')},
        ),
        migrations.AddField(
            model_name='promoterregistryentry',
            name='cash_collected',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-sum from CASH transactions via mobile. HR can override.', max_digits=12),
        ),
        migrations.AddField(
            model_name='promoterregistryentry',
            name='cash_submitted',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Physical cash submitted by the promoter at the office.', max_digits=12),
        ),
        migrations.AddField(
            model_name='promoterregistryentry',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promoterregistryentry',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoter_closings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promoterregistryentry',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='When True, the promoter cannot make new collections for this date.'),
        ),
        migrations.AddField(
            model_name='promoterregistryentry',
            name='online_collected',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-sum from UPI/online transactions via mobile. HR can override.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='promoterregistryentry',
            name='ending_reading',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promoterregistryentry',
            name='entry_code',
            field=models.CharField(blank=True, default='', help_text='e.g. VR250528001', max_length=50),
        ),
        migrations.AlterField(
            model_name='promoterregistryentry',
            name='starting_reading',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='promoterregistryentry',
            name='cash_amount',
        ),
        migrations.RemoveField(
            model_name='promoterregistryentry',
            name='online_amount',
        ),
        migrations.RemoveField(
            model_name='promoterregistryentry',
            name='promoter_reading',
        ),
        migrations.RemoveField(
            model_name='promoterregistryentry',
            name='total_amount',
        ),
    ]
