# Generated by Django 5.2.7 on 2026-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0012_promoter_registry_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffvoucherbook',
            name='next_book_number',
            field=models.PositiveIntegerField(blank=True, help_text='Queued next book number', null=True),
        ),
        migrations.AddField(
            model_name='staffvoucherbook',
            name='next_voucher_end',
            field=models.PositiveIntegerField(blank=True, help_text='Last voucher number of next book', null=True),
        ),
        migrations.AddField(
            model_name='staffvoucherbook',
            name='next_voucher_start',
            field=models.PositiveIntegerField(blank=True, help_text='First voucher number of next book', null=True),
        ),
    ]
