# Generated by Django 5.2.7 on 2026-08-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0013_staffvoucherbook_next_book_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/photos/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/photos/'),
        ),
    ]
