# Generated by Django 5.2.7 on 2026-08-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0014_attendance_check_in_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoterregistryentry',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified')], default='UNVERIFIED', help_text='Indicates if the entry has been verified in the Verification Dashboard.', max_length=20),
        ),
    ]
