# Generated by Django 5.2.7 on 2026-09-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0017_alter_staffvoucherbook_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiveofficer',
            name='termination_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executiveofficer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PROBATION', 'Probation'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated'), ('RETIRED', 'Retired'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
    ]
