# Generated by Django 5.2.7 on 2026-08-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('CASHIER', 'Cashier'), ('HR', 'HR'), ('FIELD_ASSESSMENT_OFFICER', 'Field Assessment Officer'), ('ASSESSMENT_CALCULATION_OFFICER', 'Assessment Calculation Officer'), ('GENERAL_ENQUIRY_OFFICER', 'General Enquiry Officer'), ('STAFF', 'Staff'), ('MEMBER', 'Member')], default='MANAGER', max_length=35),
        ),
    ]
