# Generated by Django 5.2.7 on 2026-08-24 08:39

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/', validators=[core.validators.validate_image_file]),
        ),
    ]
