# Generated by Django 5.2.7 on 2026-08-26 10:33

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
