# Generated by Django 5.2.7 on 2026-08-29 07:49

from django.db import migrations


def populate_staff_uid(apps, schema_editor):
    User = apps.get_model('core', 'User')
    counter = 1
    # Only populate for internal staff (exclude MEMBER and None)
    for user in User.objects.exclude(role='MEMBER').exclude(role__isnull=True).order_by('date_joined'):
        if not user.staff_uid:
            user.staff_uid = f"SLT-{counter:04d}"
            user.save(update_fields=['staff_uid'])
            counter += 1

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_staff_uid'),
    ]

    operations = [
        migrations.RunPython(populate_staff_uid, reverse_code=migrations.RunPython.noop),
    ]
