# Generated by Django 5.2.7 on 2026-08-29 08:31

import core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_populate_staff_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(default='Upcoming', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', validators=[core.validators.validate_image_file])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_events',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
