# Generated by Django 5.2.7 on 2026-08-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleFeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('HR', 'HR'), ('DATA_ENTRY', 'Data Entry'), ('FIELD_ASSESSMENT_OFFICER', 'Field Assessment Officer'), ('ASSESSMENT_CALCULATION_OFFICER', 'Assessment Calculation Officer'), ('GENERAL_ENQUIRY_OFFICER', 'General Enquiry Officer'), ('STAFF', 'Staff'), ('MEMBER', 'Member')], max_length=35)),
                ('feature_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_role_features',
                'unique_together': {('role', 'feature_key')},
            },
        ),
    ]
