# Generated by Django 5.2.7 on 2026-08-30 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rolefeaturepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpoDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expo_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_expo_devices',
                'ordering': ['-updated_at'],
            },
        ),
    ]
