# Generated by Django 5.2.7 on 2026-08-10 19:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashClosing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('system_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('physical_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('DISPUTED', 'Disputed')], default='SUBMITTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cashier_cash_closing',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CashHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handover_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('from_confirmed', models.BooleanField(default=True)),
                ('to_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cashier_handovers',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disbursement_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('NEFT', 'NEFT'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('voucher_number', models.CharField(blank=True, max_length=50)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_signature', models.ImageField(blank=True, null=True, upload_to='disbursements/signatures/')),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='disbursements/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cashier_disbursements',
                'ordering': ['-date'],
            },
        ),
    ]
