# Generated by Django 5.2.7 on 2026-08-10 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashier_module', '0001_initial'),
        ('manager_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashclosing',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_closings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashclosing',
            name='closed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_closings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='from_cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='disbursed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement', to='manager_module.assessmentrequest'),
        ),
    ]
