# Generated by Django 5.2.7 on 2026-08-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier_module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashclosing',
            name='bank_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashclosing',
            name='physical_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashclosing',
            name='system_bank_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
