# Generated by Django 5.2.7 on 2026-08-24 08:39

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier_module', '0003_cashclosing_bank_difference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='disbursements/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='receiver_signature',
            field=models.ImageField(blank=True, null=True, upload_to='disbursements/signatures/', validators=[core.validators.validate_image_file]),
        ),
    ]
