# Generated by Django 5.2.7 on 2026-09-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier_module', '0004_alter_disbursement_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashclosing',
            name='credit_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cashclosing',
            name='debit_rows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
