name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "1. Connected to EC2 successfully!"
            
            echo "2. Going into project folder..."
            cd Trust-in
            
            echo "3. Pulling latest code from GitHub..."
            git pull origin main
            
            echo "4. Restarting the server with docker..."
            docker compose up -d --build
            
            echo "5. Deployment Complete!"